Desktop/Agro_farm/Agro_farm/urls.py
from django.urls import path, include

urlpatterns = [
    path('livestocks/', include('livestocks.urls')),
    path('admins/', include('admins.urls')),
    path('', include('accounts.urls'))
]

Desktop/Agro_farm/admins/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard', views.dashboard),
    path('all_orders',views.all_orders),
    path('delete_order/<int:delete_id>',views.delete_order),
    path("deliver/<int:id>", views.delivered),
    path("pending/<int:id>", views.pending)


]

Desktop/Agro_farm/livestocks/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('homepage', views.homepage),
    path('category_form', views.category_form),
    path('get_category', views.get_category),
    path('delete_category/<int:category_id>', views.delete_category),
    path('update_category/<int:category_id>', views.category_update_form),

    path('livestock_form', views.livestock_form),
    path('get_livestock', views.get_livestock),
    path('delete_livestock/<int:livestock_id>', views.delete_livestock),
    path('update_livestock/<int:livestock_id>', views.livestock_update_form),

    path('get_category_user', views.show_categories),
    path('get_livestock_user', views.show_livestocks),
    path('checklist', views.checklist),
    path('add_to_cart/<int:livestock_id>',views.add_to_cart),
    path('mycart', views.show_cart_items),
    path('remove_cart_item/<int:cart_id>', views.remove_cart_item),
    path('order_form/<int:livestock_id>/<int:cart_id>', views.order_form),
    path('esewa_verify', views.esewa_verify),
    path('my_order', views.my_order),

    path('password_change_user', auth_views.PasswordChangeView.as_view(
        template_name='livestocks/password_change.html')),
    path('password_change_done_user', auth_views.PasswordChangeView.as_view(
        template_name='livestocks/password_change_done.html'), name='password_change_done')


]

Desktop/Agro_farm/livestocks/models.py
from django.db import models
from django.core.validators import *
from django.core import validators
from django.contrib.auth.models import User


class Category(models.Model):
    category_name = models.CharField(max_length=200, null=True, validators=[validators.MinLengthValidator(2)])
    category_description = models.TextField(null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    category_image = models.FileField(upload_to='static/uploads', null=True)

    def __str__(self):
        return self.category_name


class Livestock(models.Model):
    livestock_name = models.CharField(max_length=200)
    livestock_price = models.FloatField()
    livestock_image = models.FileField(upload_to='static/uploads')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.livestock_name


class Cart(models.Model):
    livestock = models.ForeignKey(Livestock, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered'),
    )
    PAYMENT = (
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Esewa', 'Esewa'),
        ('Khalti', 'Khalti'),
    )
    livestock = models.ForeignKey(Livestock, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    quantity = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(1000)])
    total_price = models.IntegerField(null=True)
    status = models.CharField(max_length=200, choices=STATUS, null=True)
    payment_method = models.CharField(max_length=200, choices=PAYMENT, null=True)
    payment_status = models.BooleanField(default=False, null=True, blank=True)
    contact_no = models.CharField(validators=[MinLengthValidator(9), MaxLengthValidator(10)], null=True, max_length=10)
    contact_address = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)

Desktop/Agro_farm/livestocks/forms.py
from django import forms
from django.forms import ModelForm

from .models import Category, Livestock, Order

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class LivestockForm(ModelForm):
    class Meta:
        model = Livestock
        fields = "__all__"


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['quantity', 'contact_no', 'contact_address', 'payment_method']

Desktop/Agro_farm/livestocks/views.py
from django.shortcuts import render, redirect
from .forms import CategoryForm, LivestockForm, OrderForm
from django.contrib import messages
from .models import Category, Livestock, Cart, Order
from accounts.auth import admin_only, user_only
from django.contrib.auth.decorators import login_required
import os
# from .filters import LivestockFilter


@user_only
def homepage(request):
    return render(request, 'livestocks/homepage.html')

@login_required
@admin_only
def category_form(request):
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category added successfully')
            return redirect("/livestocks/get_category")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add category')
            return render(request, 'livestocks/category_form.html', {'form_category': form})
    context = {
        'form_category': CategoryForm,
        'activate_category': 'active'
    }
    return render(request, 'livestocks/category_form.html', context)


@login_required
@admin_only
def get_category(request):
    categories = Category.objects.all().order_by('-id')
    context = {
        'categories': categories,
        'activate_category': 'active'
    }
    return render(request, 'livestocks/get_category.html', context)


@login_required
@admin_only
def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    messages.add_message(request, messages.SUCCESS, 'Category Deleted Successfully')
    return redirect('/livestocks/get_category')

@login_required
@admin_only
def category_update_form(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == "POST":
        form = CategoryForm(request.POST,instance=category)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category updated successfully')
            return redirect("/livestocks/get_category")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update category')
            return render(request, 'livestocks/category_update_form.html', {'form_category':form})
    context ={
        'form_category': CategoryForm(instance=category),
        'activate_category': 'active'
    }
    return render(request, 'livestocks/category_update_form.html', context)




@login_required
@admin_only
def livestock_form(request):
    if request.method == "POST":
        form = LivestockForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Livestock added successfully')
            return redirect("/livestocks/get_livestock")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add Livestock')
            return render(request, 'livestocks/livestock_form.html', {'livestock_food': form})
    context ={
        'form_livestock': LivestockForm,
        'activate_livestock': 'active'
    }
    return render(request, 'livestocks/livestock_form.html', context)


@login_required
@admin_only
def get_livestock(request):
    livestocks = Livestock.objects.all().order_by('-id')
    context = {
        'livestock': livestocks,
        'activate_livestock': 'active'
    }
    return render(request, 'livestocks/get_livestock.html', context)


@login_required
@admin_only
def delete_livestock(request, livestock_id):
    livestock = Livestock.objects.get(id=livestock_id)
    os.remove(livestock.food_image.path)
    livestock.delete()
    messages.add_message(request, messages.SUCCESS, 'Livestock Deleted Successfully')
    return redirect('/livestocks/get_livestock')


@login_required
@admin_only
def livestock_update_form(request, livestock_id):
    livestock = Livestock.objects.get(id=livestock_id)
    if request.method == "POST":
        if request.FILES.get('livestock_image'):
            os.remove(livestock.livestock_image.path)
        form = LivestockForm(request.POST, request.FILES, instance=livestock)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Livestock updated successfully')
            return redirect("/livestocks/get_livestock")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update livestock')
            return render(request, 'livestocks/livestock_form.html', {'form_livestock':form})
    context ={
        'form_livestock': LivestockForm(instance=livestock),
        'activate_livestock': 'active'
    }
    return render(request, 'livestocks/livestock_update_form.html', context)


@login_required
@user_only
def show_categories(request):
    categories = Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        'activate_category_user': 'active'
    }
    return render(request, 'livestocks/show_categories.html', context)

@login_required
@user_only
def show_livestocks(request):
    print("1")
    if 'q' in request.GET:
        q = request.GET['q']
        print("here")
        livestocks = Livestock.objects.filter(livestock_name__icontains=q)
    else:
        livestocks = Livestock.objects.all().order_by('-id')
    context = {
        'livestock': livestocks,
        'activate_livestock_user': 'active'
    }
    return render(request, 'livestocks/show_livestocks.html', context)


@login_required
@user_only
def checklist(request):
    categories  = Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        'activate_checklist':'active'
    }
    return render(request, 'livestocks/checklist.html', context)


@login_required
@user_only
def add_to_cart(request, livestock_id):
    user = request.user
    livestock = Livestock.objects.get(id=livestock_id)

    check_item_presence = Cart.objects.filter(user=user, livestock=livestock)
    if check_item_presence:
        messages.add_message(request, messages.ERROR, 'Item is already present in cart')
        return redirect('/livestocks/get_livestock_user')
    else:
        cart = Cart.objects.create(livestock=livestock, user=user)
        if cart:
            messages.add_message(request, messages.SUCCESS, 'Item added to cart')
            return redirect('/livestocks/mycart')
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add item to cart')


@login_required
@user_only
def show_cart_items(request):
    user = request.user
    items = Cart.objects.filter(user= user)
    context = {
        'items': items,
        'activate_my_cart':'active'
    }
    return render(request, 'livestocks/mycart.html', context)


@login_required
@user_only
def remove_cart_item(request, cart_id):
    item = Cart.objects.get(id=cart_id)
    item.delete()
    messages.add_message(request, messages.SUCCESS, 'Cart item removed successfully')
    return redirect('/livestocks/mycart')


@login_required
@user_only
def order_form(request, livestock_id, cart_id):
    user = request.user
    livestock = Livestock.objects.get(id=livestock_id)
    cart_item = Cart.objects.get(id=cart_id)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            quantity = request.POST.get('quantity')
            price = livestock.livestock_price
            total_price = int(quantity) * int(price)
            contact_no = request.POST.get('contact_no')
            contact_address = request.POST.get('contact_address')
            payment_method = request.POST.get('payment_method')
            order = Order.objects.create(livestock=livestock,
                                         user=user,
                                         quantity=quantity,
                                         total_price=total_price,
                                         contact_no=contact_no,
                                         contact_address=contact_address,
                                         status="Pending",
                                         payment_method=payment_method,
                                         payment_status=False
                                         )
            if order:
                messages.add_message(request, messages.SUCCESS, 'Item Ordered Successfully. ')
                cart_item.delete()
                context = {
                    'order': order,
                    'cart': cart_item
                }
                return render(request, 'livestocks/esewa_payment.html', context)
        else:
                messages.add_message(request, messages.ERROR, 'Something went wrong')
                return render(request, 'livestocks/order_form.html', {'order_form': form})

    context = {
        'order_form': OrderForm
    }
    return render(request,'livestocks/order_form.html', context)



def esewa_verify(request):
    import xml.etree.ElementTree as ET
    o_id = request.GET.get('oid')
    amount = request.GET.get('amt')
    refId = request.GET.get('refId')
    url = "https://uat.esewa.com.np/epay/transrec"
    d = {
        'amt': amount,
        'scd': 'EPAYTEST',
        'rid': refId,
        'pid': o_id,
    }
    resp = request.post(url, d)
    root = ET.fromstring(resp.content)
    status = root[0].text.strip()
    if status == 'Success':
        order_id = o_id.split("_")[0]
        order = Order.objects.get(id=order_id)
        order.payment_status = True
        order.save()
        cart_id = o_id.split("_")[1]
        cart = Cart.objects.get(id=cart_id)
        cart.delete()
        messages.add_message(request, messages.SUCCESS, 'Payment Successful')
        return redirect('/livestocks/my_order')
    else:
        messages.add_message(request, messages.ERROR, 'Unable to make payment')
        return redirect('/livestocks/mycart')


@login_required
@user_only

Desktop/Agro_farm/livestocks/templates/Livestocks/category_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add New Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter category name"
    form_fields[2].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/category_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter category name"
    form_fields[2].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/checklist.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Checklist</title>
{% endblock title %}

{% block main_content %}
<h1>All Categories With Livestocks</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories %}
        <h1>{{i.category_name}}</h1>
          <div class="livestock_image">
       <img src="/{{i.category_image}}" width="200"/>
            </div>
        {% for j in i.livestock_set.all %}
        <div class="checklist-items d-flex justify-content-between">
            <div class="livestock_name">
                <p><strong>{{j.livestock_name}}</strong></p>
            </div>
            <div class="livestock_price">
                <strong>Rs. {{j.livestock_price }}</strong>
            </div>

        </div>
        {% endfor %}

        {% endfor %}
    </div>
</div>
{% endblock main_content %}

Desktop/Agro_farm/livestocks/templates/Livestocks/get_category.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Categories</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Categories</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/livestocks/category_form"
                >Add New Category</a>
                <table class="table-striped">
                    <tr>
                        <th>Category Name</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                    {% for i in categories %}
                    <tr>
                        <td> {{ i.category_name }}</td>
                        <td> {{ i.category_description }}</td>
                        <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/livestocks/update_category/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/livestocks/delete_category/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this category?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/get_livestock.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Livestocks</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Livestocks</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/livestocks/livestock_form"
                >Add New Livestock</a>
                <table class="table-striped">
                    <tr>
                        <th>Livestock Name</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Image</th>

                        <th>Actions</th>
                    </tr>
                    {% for i in livestock %}
                    <tr>
                        <td> {{ i.livestock_name }}</td>
                        <td> {{ i.livestock_price }}</td>
                        <td> {{ i.category.category_name }}</td>
                        <td><img src="{{i.livestock_image.url}}" width="200"> </td>
                        <td><a class="btn btn-primary btn-sm" href="/livestocks/update_livestock/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/livestocks/delete_livestock/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this livestock?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/homepage.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Users Homepage</title>
{% endblock title %}

{% block main_content %}
{% endblock main_content %}

Desktop/Agro_farm/livestocks/templates/Livestocks/livestock_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Livestock</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add New Livestock</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_livestock | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter livestock name"
    form_fields[2].placeholder = "Enter livestock price"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/livestock_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Livestock</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Livestock</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_livestock | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter livestock name"
    form_fields[2].placeholder = "Enter livestock price"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/my_order.html
{% extends 'layout.html' %}
{% block title %}
<title>MyOrders</title>
{% endblock title %}
{% block main_content %}

<div class="container-fluid" style="min-height:300px;">
    <div class="row">
        <div class="col mt-4 mb-4">
            <h1 class="text-center text-uppercase m-4 font-weight-bold">My Order History</h1>
            {% include 'messages.html' %}
            <div class="card shadow-lg ">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Item Name</th>
                            <th>Item Price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                            <th>Ordered Date</th>
                            <th>Contact No</th>
                            <th>Delivery Location</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody class="align-items-center">
                        {% for item in items %}
                        <tr >
                            <td>{{item.livestock.livestock_name}}</td>
                            <td>Rs.{{item.livestock.livestock_price}}</td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.total_price}}</td>
                            <td>{{item.created_date}}</td>
                            <td>{{item.contact_no}}</td>
                            <td>{{item.contact_address}}</td>
                            <td>{{item.status}}</td>
                                                    </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/mycart.html
{% extends 'layout.html' %}
{% block title %}
<title>My Cart </title>
{% endblock%}
{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">My Cart</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <table class="table-striped">
                    <tr>
                        <th>Livestock Name</th>
                        <th>Livestock Price</th>
                        <th>Date Added</th>
                        <th>Actions</th>
                    </tr>
                    {% for i in items %}
                    <tr>
                        <td> {{ i.livestock.livestock_name }}</td>
                        <td> {{ i.livestock.livestock_price }}</td>
                        <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/livestocks/remove_cart_item/{{i.id}}">Remove</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/livestocks/order_form/{{i.livestock.id}}/{{i.id}}"
                               onclick="return confirm('Are you sure want to order this livestock?')" >Order</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/order_form.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %}
    <title>Order Item</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Order Item</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ order_form | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Proceed to Payment</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter quantity"
    form_fields[2].placeholder = "Enter contact no"
       form_fields[3].placeholder = "Enter contact address"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/password_change.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %}
<title>Change Password</title>
{% endblock%}

{% block main_content %}

<div class="container">
    <div class="row">

        <div class="col-md-8 offset-md-2">

            <h1 class="text-center">Change Password</h1>
            <div class="card py-2 px-2">
                <form class="form myForm" action="" method="POST">
                    {% csrf_token %}
                    {{ form | bootstrap_horizontal }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Enter old password';
    form_fields[2].placeholder = 'Enter new password';
    form_fields[3].placeholder = 'Enter new password again';


    for (var field in form_fields){
    form_fields[field].className += ' my-2'
    }

</script>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/password_change_done.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %}
<title>Change Password</title>
{% endblock%}

{% block main_content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center">Password Change Completed</h1>
            <div class="card py-2 px-2 bg-success">
                <h4 class="text-center text-white">Congratulations! Your password has been changed successfully.</h4>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Desktop/Agro_farm/livestocks/templates/Livestocks/show_categories.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Categories</title>
{% endblock title %}

{% block main_content %}
<h1>All Categories</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories %}
        <div class="card col-md-3">
            <img src="/{{i.category_image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.category_name}}</h5>
                <p class="card-text">{{i.category_description}}</p>

                <a href="/livestocks/checklist" class="btn btn-primary">View Price Details</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock main_content %}